title:              Jaewook J. Suh
email:              jacksuh@rice.edu
description:        
author:             Jaewook J. Suh
baseurl:            ""
url:                "https://jaewookjsuh.github.io"

# Social Profiles
twitter_username:   
github_username: jaewookjsuh   
facebook_username:  
instagram_username:  
linkedin_username:
scholar_id: C9rAAAEAAAAJ

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

# # Customizing
# kramdown:
#   math_engine: katex
# katex: true